#!/bin/bash

source ./functions.sh

showDiff() {
    {
        git -c color.ui=always diff
    } | labeledOutput $LABEL
}

{
    eachRepo parallel buffered "checking \`git diff\` in each repo" \
        showDiff
 } | optionalPager

echo >&2
echo "To commit changes in these repos, run ./commit-all" >&2
