#!/bin/bash

source ./functions.sh

showStatus() {
    {
#        git -c color.ui=always status --short  -b 
        RESULTS=$({ 
            git  -c color.ui=always status --show-stash | 
            grep -v "Your branch is up to date with" |
            grep -v "no changes added to commit" |
            grep -v "Changes not staged for commit" |
            grep -v "working tree clean" |
            grep -v "what will be committed" |
            grep -v "to discard changes in working directory" |
            grep -v "git restore --staged" |
            grep -v "^On branch " |
            grep -ve "^\s*$" |
            cat
        })
        [[ -z $RESULTS ]] || {
            echo "$RESULTS"
            echo "--------------------------------------------------"
        }
    } | labeledOutput $LABEL
}

{
    eachRepo parallel buffered "checking \`git status\` in each repo" \
        showStatus
 } | optionalPager

echo >&2
echo "To commit changes in these repos, run ./commit-all" >&2

