#!/bin/bash

source ./functions.sh
source .fork-config

#  HAVE_DIFFS=$(./gsall 2>/dev/null | cut -d ' ' -f1 | uniq )

gitStatus() {
    git -c color.ui=always status --short  -b | labeledOutput $LABEL
}
gitStatusPlain() {
    git status --short  -b | labeledOutput $DIR
}
# eachRepo parallel buffered "checking \`git status\` in each repo" gitStatus

HAVE_DIFFS=$(
    eachRepo parallel buffered "project with diffs" gitStatusPlain | cut -d ' ' -f1 | uniq
)
# echo "$HAVE_DIFFS"

filters=$(
    echo "$HAVE_DIFFS" | while read REPO ; do {
        echo "--filter $REPO"
    } done
)

# echo "Repos with changes to be committed:"
# echo "$HAVE_DIFFS" | while read REPO; do
#     echo " - $REPO"
# done

NEED=$( 
    pnpm -r $filters exec bash -c 'basename $(pwd)'  2> >(labeledErrors "pnpm") | grep -v "No projects matched"
)
# pnpm -r $filters exec $COMMIT_TOOL

show() {
    echo "Reviewing repos with changes to be committed:"
    echo
    echo "$NEED" | while read REPO; do
        echo " - $REPO"
    done
    echo
}
show
for a in $NEED; do
    echo "  $a"
    # wait for 3 seconds before automatically moving to the next repo
    read -t 3 -p "Press Enter to continue or Ctrl-C to exit"
    pushd $a  >/dev/null
    LABEL=$a gitStatus
    pnpm install --ignore-workspace
    pnpm build
    echo "Spawning bash for $a ..."
    echo " ... exit the shell when done committing ..."
    bash --noprofile
    popd >/dev/null
    echo
    echo "... done with $a"
done

echo "Rerun ./need-commits to review remaining repos"
exit

