packages:
  - "cbor"
  - "cli"
  - "cli-utils"
  - "codec-utils"
  - "compat"
  - "compiler"
  - "compiler-utils"
  - "contract-utils"
  - "crypto"
  - "era"
  - "esbuild-plugin"
  - "ir"
  - "ledger"
  - "ledger-allegra"
  - "ledger-alonzo"
  - "ledger-babbage"
  - "ledger-byron"
  - "ledger-conway"
  - "ledger-mary"
  - "ledger-shelley"
  - "rollup-plugin"
  - "tx-utils"
  - "type-utils"
  - "uplc"
  