#!/usr/bin/env bash

source ./functions.sh

cloneIfNeeded() {
    [[ -d $REPO/.git ]] || {
        set -e
        git clone https://github.com/HeliosLang/$REPO
        set +e
    } 
}
eachRepo parallel buffered nocd \
     "cloning repos" cloneIfNeeded 
    # 

fetchAll() {
    {
        git fetch --all
        git pull
    } | labeledOutput $LABEL
}

eachRepo parallel buffered "fetching and updating repos" \
    fetchAll | optionalPager

echo
echo "All repos fetched and updated."
echo "Next: install dependencies (Ctrl-C to cancel) for all repos"
echo
read -p"Next: $ " -e -i"pnpm install" COMMAND_IGNORED

pnpm install

echo
